### ISSUE TITLE
Installing Sprinter in Ubuntu

### ISSUE THREAD

**Issue by allenkubai** [toumorokoshi/sprinter#99]
allen@Kub-01:~$ cd /tmp/; rm sandbox.sh; wget https://raw.githubusercontent.com/toumorokoshi/sprinter/master/scripts/sandbox.sh -O sandbox.sh; bash sandbox.sh
--2016-09-19 21:42:15--  https://raw.githubusercontent.com/toumorokoshi/sprinter/master/scripts/sandbox.sh
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 151.101.16.133
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|151.101.16.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 1824 (1.8K) [text/plain]
Saving to: ‘sandbox.sh’

sandbox.sh                                 100%[=====================================================================================>]   1.78K  --.-KB/s    in 0s      

2016-09-19 21:42:16 (317 MB/s) - ‘sandbox.sh’ saved [1824/1824]

Creating sandbox directory...
Downloading sprinter...
URL transformed to HTTPS due to an HSTS policy
--2016-09-19 21:42:17--  https://github.com/toumorokoshi/sprinter/tarball/master
Resolving github.com (github.com)... 192.30.253.113
Connecting to github.com (github.com)|192.30.253.113|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://codeload.github.com/toumorokoshi/sprinter/legacy.tar.gz/master [following]
--2016-09-19 21:42:18--  https://codeload.github.com/toumorokoshi/sprinter/legacy.tar.gz/master
Resolving codeload.github.com (codeload.github.com)... 192.30.253.121
Connecting to codeload.github.com (codeload.github.com)|192.30.253.121|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 81605 (80K) [application/x-gzip]
Saving to: ‘sprinter.tar.gz’

sprinter.tar.gz                            100%[=====================================================================================>]  79.69K   160KB/s    in 0.5s    

2016-09-19 21:42:19 (160 KB/s) - ‘sprinter.tar.gz’ saved [81605/81605]

Creating python sandbox...
Downloading uranium from https://raw.githubusercontent.com/toumorokoshi/uranium/master/uranium/scripts/uranium_standalone
loading uranium bootstrapper...
installing virtualenv...
Downloading url: https://pypi.python.org/packages/source/v/virtualenv/virtualenv-15.0.2.tar.gz
url https://pypi.python.org/packages/source/v/virtualenv/virtualenv-15.0.2.tar.gz failed. Attempting fallback...
Downloading url: https://github.com/pypa/virtualenv/archive/15.0.2.tar.gz
extracting to /tmp/tmpadVzQU...
New python executable in /tmp/sprinter-sandbox-allen/.uranium/bin/python
Installing setuptools, pip, wheel...done.
setting up uranium...
done!
[21:42:31] executing uranium in /tmp/sprinter-sandbox-allen...
Using real prefix '/usr'
New python executable in /tmp/sprinter-sandbox-allen/bin/python
Installing setuptools, wheel...done.
[21:42:33] === START URANIUM ===
[21:42:34] Obtaining sprinter==1.4.2 from file:///tmp/sprinter-sandbox-allen
[21:42:34] Collecting clint>=0.3.3 (from sprinter==1.4.2)
[21:42:34] Starting new HTTPS connection (1): pypi.python.org
[21:42:35] Collecting docopt>=0.6.1 (from sprinter==1.4.2)
[21:42:35] Collecting pex==1.1.0 (from sprinter==1.4.2)
[21:42:36] Downloading pex-1.1.0-py2.py3-none-any.whl (96kB)
    100% |████████████████████████████████| 102kB 163kB/s 
[21:42:36] Collecting pip==7.1.2 (from sprinter==1.4.2)
[21:42:37] Downloading pip-7.1.2-py2.py3-none-any.whl (1.1MB)
    100% |████████████████████████████████| 1.1MB 7.0MB/s 
[21:42:37] Collecting requests>=2.3.0 (from sprinter==1.4.2)
[21:42:38] Downloading requests-2.11.1-py2.py3-none-any.whl (514kB)
    100% |████████████████████████████████| 522kB 228kB/s 
[21:42:39] Collecting six>=1.4.1 (from sprinter==1.4.2)
[21:42:39] Downloading six-1.10.0-py2.py3-none-any.whl
[21:42:39] Collecting virtualenv>=1.11.6 (from sprinter==1.4.2)
[21:42:40] Downloading virtualenv-15.0.3-py2.py3-none-any.whl (3.5MB)
    100% |████████████████████████████████| 3.5MB 3.8MB/s 
[21:42:41] Collecting args (from clint>=0.3.3->sprinter==1.4.2)
[21:42:42] Collecting setuptools<16,>=2.2 (from pex==1.1.0->sprinter==1.4.2)
[21:42:42] Downloading setuptools-15.2-py2.py3-none-any.whl (501kB)
    100% |████████████████████████████████| 512kB 941kB/s 
[21:42:43] Installing collected packages: args, clint, docopt, setuptools, pex, pip, requests, six, virtualenv, sprinter
[21:42:43] changing mode of /tmp/sprinter-sandbox-allen/bin/easy_install to 775
[21:42:43] changing mode of /tmp/sprinter-sandbox-allen/bin/easy_install-2.7 to 775
[21:42:43] changing mode of /tmp/sprinter-sandbox-allen/bin/pex to 775
[21:42:44] changing mode of /tmp/sprinter-sandbox-allen/bin/pip to 775
[21:42:44] changing mode of /tmp/sprinter-sandbox-allen/bin/pip2 to 775
[21:42:44] changing mode of /tmp/sprinter-sandbox-allen/bin/pip2.7 to 775
[21:42:44] changing mode of /tmp/sprinter-sandbox-allen/bin/virtualenv to 775
[21:42:44] Running setup.py develop for sprinter
[21:42:44] Successfully installed args-0.1.0 clint-0.5.1 docopt-0.6.2 pex-1.1.0 pip-7.1.2 requests-2.11.1 setuptools-27.2.0 six-1.10.0 sprinter virtualenv-15.0.3
[21:42:44] === URANIUM FINISHED ===
Removing sprinter environment if it already exists...
Traceback (most recent call last):
  File "bin/sprinter", line 8, in <module>
    from pkg_resources import load_entry_point
  File "/tmp/sprinter-sandbox-allen/lib/python2.7/site-packages/pkg_resources/__init__.py", line 3070, in <module>
    @_call_aside
  File "/tmp/sprinter-sandbox-allen/lib/python2.7/site-packages/pkg_resources/__init__.py", line 3056, in _call_aside
    f(*args, **kwargs)
  File "/tmp/sprinter-sandbox-allen/lib/python2.7/site-packages/pkg_resources/__init__.py", line 3083, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/tmp/sprinter-sandbox-allen/lib/python2.7/site-packages/pkg_resources/__init__.py", line 647, in _build_master
    return cls._build_from_requirements(__requires__)
  File "/tmp/sprinter-sandbox-allen/lib/python2.7/site-packages/pkg_resources/__init__.py", line 660, in _build_from_requirements
    dists = ws.resolve(reqs, Environment())
  File "/tmp/sprinter-sandbox-allen/lib/python2.7/site-packages/pkg_resources/__init__.py", line 833, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'pip==7.1.0' distribution was not found and is required by sprinter
Installing global sprinter...
Traceback (most recent call last):
  File "bin/sprinter", line 8, in <module>
    from pkg_resources import load_entry_point
  File "/tmp/sprinter-sandbox-allen/lib/python2.7/site-packages/pkg_resources/__init__.py", line 3070, in <module>
    @_call_aside
  File "/tmp/sprinter-sandbox-allen/lib/python2.7/site-packages/pkg_resources/__init__.py", line 3056, in _call_aside
    f(*args, **kwargs)
  File "/tmp/sprinter-sandbox-allen/lib/python2.7/site-packages/pkg_resources/__init__.py", line 3083, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/tmp/sprinter-sandbox-allen/lib/python2.7/site-packages/pkg_resources/__init__.py", line 647, in _build_master
    return cls._build_from_requirements(__requires__)
  File "/tmp/sprinter-sandbox-allen/lib/python2.7/site-packages/pkg_resources/__init__.py", line 660, in _build_from_requirements
    dists = ws.resolve(reqs, Environment())
  File "/tmp/sprinter-sandbox-allen/lib/python2.7/site-packages/pkg_resources/__init__.py", line 833, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'pip==7.1.0' distribution was not found and is required by sprinter
!!
Issue installing global sprinter!

I have pip 8.1.2 installed.

**Comment by jkusachi** [comment]
@allenkubai did you ever get this to work? seeing the same thing
